name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: .devcontainer/Dockerfile
        target: base-python
        tags: dddlab/base-python:latest
        load: true
    - name: Build book
      run: |
        docker run \
          --rm \
          -u root \
          -v ${PWD}/diy_ds_cloud_book:/home/jovyan/diy_ds_cloud_book \
          dddlab/base-python:latest \
          jupyter-book build diy_ds_cloud_book
    - name: Copy to GitHub Pages branch
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: diy_ds_cloud_book/_build/html